server:
  port: 9005
  servlet:
    context-path: /doc-user-api

spring:
  application:
    name: doc-user
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/