spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wg_doc_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver